### ISSUE TITLE
LineLayer draws lines differently with the same StrokeDashArray

### ISSUE THREAD

**Issue by pseabury** [arnaudleclerc/AzureMapsControl.Components#30] opened 2021-01-24 16:40 UTC
```
_connectionLines = new LineLayer
        {
            Options = new LineLayerOptions
            {
                Source = _connectionLinesSource.Id,
                StrokeColor = new ExpressionOrString("#000000"),
                StrokeWidth = new ExpressionOrNumber(6),
                StrokeDashArray = new List<double>() { 3, 3 },
                Blur = new ExpressionOrNumber(4)
            }
        };
```

It seems like depending on the angle & length of the line, the dash array gets compressed or expanded.

These are 4 separate LineStrings with only 2 Points each added to the layer.

![image](https://user-images.githubusercontent.com/1918526/105636863-d54d0300-5e2f-11eb-8e64-616a5d8bc6b9.png)

I think I expect the line to have the same dash size/spacing no matter what angle and how far apart each point is.  See the [AzureMaps LineLayer Options Example](https://azuremapscodesamples.azurewebsites.net/?sample=Line%20Layer%20Options)

![image](https://user-images.githubusercontent.com/1918526/105636969-7e93f900-5e30-11eb-95a6-6cb2bafea738.png)

**Comment by arnaudleclerc** [comment] 2021-01-25 09:52
You are right, they should look the same. I can reproduce the issue within a blazor application and not with a native one. My first guess would be that some default values are not given properly to the `azure-maps-control` library. I will take a look at it

**Comment by arnaudleclerc** [comment] 2021-01-27 09:27
On the options of your `DataSource`, do you have the `LineMetrics` property set to true by any chance ? If so, try to remove it or set it to false, it seems to be linked to the issue.

With `LineMetrics` enabled :
```
public async Task OnMapReady(MapEventArgs events)
    {
        const string dataSourceId = "dataSource";
        var dataSource = new AzureMapsControl.Components.Data.DataSource(dataSourceId)
        {
            Options = new Components.Data.DataSourceOptions
            {
                LineMetrics = true
            }
        };
        await events.Map.AddSourceAsync(dataSource);

        var firstLineString = new AzureMapsControl.Components.Atlas.LineString(new[] {
            new AzureMapsControl.Components.Atlas.Position(11.575448498549266, 48.13755069574043),
            new AzureMapsControl.Components.Atlas.Position(11.58676756971354, 48.140047150071254)
        });

        var secondLineString = new AzureMapsControl.Components.Atlas.LineString(new[] {
            new AzureMapsControl.Components.Atlas.Position(11.58676756971354, 48.140047150071254),
            new AzureMapsControl.Components.Atlas.Position(11.577539359103783, 48.14292807612109)
        });

        var thirdLineString = new AzureMapsControl.Components.Atlas.LineString(new[]
        {
            new AzureMapsControl.Components.Atlas.Position(11.580642783206272, 48.14934361032725),
            new AzureMapsControl.Components.Atlas.Position(11.572355742728753, 48.147306207317044)
        });

        var fourthLineString = new AzureMapsControl.Components.Atlas.LineString(new[]
        {
            new AzureMapsControl.Components.Atlas.Position(11.572355742728753, 48.147306207317044),
            new AzureMapsControl.Components.Atlas.Position(11.614913328471639, 48.14345895021401)
        });

        await dataSource.AddAsync(firstLineString, secondLineString, thirdLineString, fourthLineString);

        var layer = new AzureMapsControl.Components.Layers.LineLayer
        {
            Options = new Components.Layers.LineLayerOptions
            {
                Source = dataSourceId,
                StrokeColor = new Components.Atlas.ExpressionOrString("#000000"),
                StrokeDashArray = new List<double>() { 3, 3 },
                StrokeWidth = new Components.Atlas.ExpressionOrNumber(6),
                Blur = new Components.Atlas.ExpressionOrNumber(4),

            }
        };

        await events.Map.AddLayerAsync(layer);
    }
```

![image](https://user-images.githubusercontent.com/9578038/105970958-3a9c3080-608a-11eb-8c81-1aa19b55aaa2.png)


Without `LineMetrics` : 
```
public async Task OnMapReady(MapEventArgs events)
    {
        const string dataSourceId = "dataSource";
        var dataSource = new AzureMapsControl.Components.Data.DataSource(dataSourceId);
        await events.Map.AddSourceAsync(dataSource);

        var firstLineString = new AzureMapsControl.Components.Atlas.LineString(new[] {
            new AzureMapsControl.Components.Atlas.Position(11.575448498549266, 48.13755069574043),
            new AzureMapsControl.Components.Atlas.Position(11.58676756971354, 48.140047150071254)
        });

        var secondLineString = new AzureMapsControl.Components.Atlas.LineString(new[] {
            new AzureMapsControl.Components.Atlas.Position(11.58676756971354, 48.140047150071254),
            new AzureMapsControl.Components.Atlas.Position(11.577539359103783, 48.14292807612109)
        });

        var thirdLineString = new AzureMapsControl.Components.Atlas.LineString(new[]
        {
            new AzureMapsControl.Components.Atlas.Position(11.580642783206272, 48.14934361032725),
            new AzureMapsControl.Components.Atlas.Position(11.572355742728753, 48.147306207317044)
        });

        var fourthLineString = new AzureMapsControl.Components.Atlas.LineString(new[]
        {
            new AzureMapsControl.Components.Atlas.Position(11.572355742728753, 48.147306207317044),
            new AzureMapsControl.Components.Atlas.Position(11.614913328471639, 48.14345895021401)
        });

        await dataSource.AddAsync(firstLineString, secondLineString, thirdLineString, fourthLineString);

        var layer = new AzureMapsControl.Components.Layers.LineLayer
        {
            Options = new Components.Layers.LineLayerOptions
            {
                Source = dataSourceId,
                StrokeColor = new Components.Atlas.ExpressionOrString("#000000"),
                StrokeDashArray = new List<double>() { 3, 3 },
                StrokeWidth = new Components.Atlas.ExpressionOrNumber(6),
                Blur = new Components.Atlas.ExpressionOrNumber(4),

            }
        };

        await events.Map.AddLayerAsync(layer);
    }
```

![image](https://user-images.githubusercontent.com/9578038/105970596-d5483f80-6089-11eb-87da-2ec81677f769.png)

**Comment by pseabury** [comment] 2021-01-27 13:37
@arnaudleclerc - yes that was it!  Thank you so much for tracking that down for me.   I'll have to read more in the docs, but I suppose LineMetrics forces each segment to carry the same number of dashes no matter the physical distance?

I appreciate the help.

Paul

**Comment by arnaudleclerc** [comment] 2021-01-27 13:59
Glad it worked 😄 

Here is all the documentation I can find about the `LineMetrics` property : https://docs.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.datasourceoptions?view=azure-maps-typescript-latest#linemetrics

As far as I understand, it allows the usage of the `StrokeGradient` property on a `LineLayer` to define a gradient which colors the line, as in the following example. Why it has an impact on the dashes is still unknown to me, but maybe this would be a question to ask on StackOverflow or the Microsoft support., the Microsoft`s PM usually answers quite fast to those questions:

```
public async Task OnMapReady(MapEventArgs events)
    {
        const string dataSourceId = "dataSource";
        var dataSource = new AzureMapsControl.Components.Data.DataSource(dataSourceId)
        {
            Options = new Components.Data.DataSourceOptions
            {
                //LineMetrics = true
            }
        };
        await events.Map.AddSourceAsync(dataSource);

        await dataSource.AddAsync(new AzureMapsControl.Components.Atlas.LineString(new[] {
            new AzureMapsControl.Components.Atlas.Position(11.575454, 48.137392),
            new AzureMapsControl.Components.Atlas.Position(11.576029, 48.137094),
            new AzureMapsControl.Components.Atlas.Position(11.577248, 48.138912),
            new AzureMapsControl.Components.Atlas.Position(11.578434, 48.138737),
            new AzureMapsControl.Components.Atlas.Position(11.578826, 48.139409),
            new AzureMapsControl.Components.Atlas.Position(11.580140, 48.139179),
            new AzureMapsControl.Components.Atlas.Position(11.581237, 48.141555),
            new AzureMapsControl.Components.Atlas.Position(11.581155, 48.141852),
            new AzureMapsControl.Components.Atlas.Position(11.581990, 48.143534),
            new AzureMapsControl.Components.Atlas.Position(11.583355, 48.143896),
            new AzureMapsControl.Components.Atlas.Position(11.583662, 48.144258),
            new AzureMapsControl.Components.Atlas.Position(11.585458, 48.145596),
            new AzureMapsControl.Components.Atlas.Position(11.587910, 48.145779),
            new AzureMapsControl.Components.Atlas.Position(11.589632, 48.146608),
            new AzureMapsControl.Components.Atlas.Position(11.590771, 48.148219),
            new AzureMapsControl.Components.Atlas.Position(11.591979, 48.150743),
            new AzureMapsControl.Components.Atlas.Position(11.592885, 48.150611),
            new AzureMapsControl.Components.Atlas.Position(11.593161, 48.150874),
            new AzureMapsControl.Components.Atlas.Position(11.593594, 48.151084),
            new AzureMapsControl.Components.Atlas.Position(11.594028, 48.151803),
            new AzureMapsControl.Components.Atlas.Position(11.592281, 48.152074)
        }));

        var layer = new AzureMapsControl.Components.Layers.LineLayer
        {
            Options = new Components.Layers.LineLayerOptions
            {
                Source = dataSourceId,
                StrokeWidth = new Components.Atlas.ExpressionOrNumber(6),
                StrokeGradient = new Components.Atlas.Expression(
                    new AzureMapsControl.Components.Atlas.Expression[]
                    {
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("interpolate"),
                        new Components.Atlas.Expression(
                            new AzureMapsControl.Components.Atlas.Expression[]
                            {
                                new AzureMapsControl.Components.Atlas.ExpressionOrString("linear")
                            }),
                        new Components.Atlas.Expression(
                            new AzureMapsControl.Components.Atlas.Expression[]
                            {
                                new AzureMapsControl.Components.Atlas.ExpressionOrString("line-progress")
                            }),
                        new AzureMapsControl.Components.Atlas.ExpressionOrNumber(0),
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("blue"),
                        new AzureMapsControl.Components.Atlas.ExpressionOrNumber(0.1),
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("royalBlue"),
                        new AzureMapsControl.Components.Atlas.ExpressionOrNumber(0.3),
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("cyan"),
                        new AzureMapsControl.Components.Atlas.ExpressionOrNumber(0.5),
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("lime"),
                        new AzureMapsControl.Components.Atlas.ExpressionOrNumber(0.7),
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("yellow"),
                        new AzureMapsControl.Components.Atlas.ExpressionOrNumber(1),
                        new AzureMapsControl.Components.Atlas.ExpressionOrString("red"),
                    })
            }
        };

        await events.Map.AddLayerAsync(layer);
    }
```

![image](https://user-images.githubusercontent.com/9578038/106000914-a218a700-60af-11eb-839d-4e13d72d3e73.png)

I will close this issue as we found the solution. Let me know if you need anything else!

**Closed by arnaudleclerc** 2021-01-27 13:59 UTC
